# Generated by Django 4.0 on 2023-12-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('books', '0002_rename_name_book_title_book_author_book_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='posted_by',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='auth.user'),
            preserve_default=False,
        ),
    ]
